### ISSUE TITLE
CRASH: Index out of range exception

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1016]
This is a major problem as I cannot continue with my Ranorex integration

![image](https://user-images.githubusercontent.com/1041237/117715880-e0d9f500-b1a6-11eb-8285-1fd7409128f0.png)

Import the attached file

Select Human
Liver
Interstitial
C1 (C1 is a compound in a project, it does not matter which)

Application:
PK-Sim® 10.0.0

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
```
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.validateDataSource(IDataSource dataSource)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.importSheets(IDataSourceFile dataSourceFile, Cache`2 sheets, String filter, String selectedNamingConvention)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.ImportSheetsFromDataPresenter(Object sender, ImportSheetsEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.ImportDataForConfirmation()
   at OSPSuite.UI.Views.Importer.ImporterDataView.onButtonImportAllClicked(Object sender, EventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```
[ObservedData.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6454625/ObservedData.xlsx)

**Comment by msevestre** [comment]
seems to be due to the Error column

**Comment by msevestre** [comment]
@abdelr @georgeDaskalakis @Yuri05  @PavelBal 
Is such format not supported anymore? I can't remember

![image](https://user-images.githubusercontent.com/1041237/117716410-8ee59f00-b1a7-11eb-9134-c78663f8daf3.png)


At the moment,. the importer barfs in a very interesting way creating a bunch of nonsensical sheets

**Comment by msevestre** [comment]
@abdelr Yeah I realized yesterday that the row 1 was hidden (no idea why)
I am wondering WHY the file was recognized as ok in the first place? 

>Also, the error you described does not happen with any compound

I meant in the project. It does not matter how I name the compound. The issue is clearly with the extra row.

**Comment by abdelr** [comment]
@msevestre :
> @abdelr Yeah I realized yesterday that the row 1 was hidden (no idea why)
> I am wondering WHY the file was recognized as ok in the first place?
No idea why. With the first row it is not recognized as valid. I guess we would need to be able to reproduce if we want to understand better.
> 
> > Also, the error you described does not happen with any compound
> 
> I meant in the project. It does not matter how I name the compound. The issue is clearly with the extra row.
Could you share the project so we could debug and see why it happens?

**Comment by msevestre** [comment]
I just created a project and added a compound loil. But yes I 'll do it again

**Comment by georgeDaskalakis** [comment]
Also from the screenshot I can see you have 3 available sheets in the importer window. Is this because the two other sheets are not included in the file you attached, or are you seeing two empty tabs? If the second is true, this could also be causing problems.

**Comment by msevestre** [comment]
Can't reproduce anymore...oh welll
