### ISSUE TITLE
Observed data import: Error when applying a configuration

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1067]
[Formate.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6569264/Formate.zip)
PK-Sim 10.0.147
* In an empty project: "`Add observed data...`"
* Select **000_TC_NoUnit.xlsx**
* Click "`Apply configuration`" and select **000_TC_NoUnit.xml**
* Click "`Load current sheet`"
* Click "`Import`"

```
Application:
PK-Sim® 10.0.147

Value cannot be null.
Parameter name: key

Stack trace:

at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Core.Domain.Project.AddImporterConfiguration(ImporterConfiguration configurationToAdd)
   at OSPSuite.Core.Commands.AddImporterConfigurationToProjectCommand.ExecuteWith(IOSPSuiteExecutionContext context)
   at OSPSuite.Core.Commands.OSPSuiteCommand`1.Execute(TContext context)
   at OSPSuite.Core.Commands.Core.CommandExtensions.Run[T,ExecutionContext](T commandToExecute, ExecutionContext context)
   at OSPSuite.Core.Domain.Services.ObservedDataTask.AddImporterConfigurationToProject(ImporterConfiguration configuration)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject()
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by georgeDaskalakis** [comment]
fixed by pull request #1067
