### ISSUE TITLE
Importer: Error when trying to import a file.

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1102]
1) Start PK-Sim
2) Try to load any data - after selecting the file, the following error is thrown:

Application:
PK-Sim® 10.0.162

Sequence contains no elements

Stack trace:
```
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at OSPSuite.Infrastructure.Import.Core.UnformattedData.AsDataTable()
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.createSheetsForViewing()
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.SetDataSource(String dataSourceFileName)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.SetSourceFile(String path)
   at OSPSuite.UI.Services.DataImporter.ImportDataSets(IReadOnlyList`1 metaDataCategories, IReadOnlyList`1 columnInfos, DataImporterSettings dataImporterSettings)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject()
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Update - not only in an empty project, so I assume something is with the file. I will send you the file.
