### ISSUE TITLE
Error when trying to add observed data without a loaded project

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1184]
In PK-Sim:

1) Open PK-Sim
2) Select "Add Observed Data..."

Application:
PK-Sim® 10.0.165

Field not found: 'ObservedData.PATIENT_ID'.

Stack trace:
```
at PKSim.Infrastructure.Services.ImportObservedDataTask.addNamingPatterns(DataImporterSettings dataImporterSettings)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.addObservedData(Func`1 importConfiguration, Compound compound, Boolean allowCompoundNameEdit)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProjectForCompound(Compound compound)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddObservedDataToProject()
   at PKSim.Presentation.UICommands.ImportConcentrationDataCommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
Ok wrong libs used..
