### ISSUE TITLE
Crash when trying to edit imported observed data set

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1220]
In PK-Sim 10: in empty project, "Add Observed data", select the file attached and import using all the default settings of the import configuration.
[016.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6884883/016.xlsx)
Then double click on one of the imported data sets: the error below appears.

Adding imported data set to charts works.

Application:
PK-Sim® 10.0.0

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Core.Domain.Data.DataRepositoryExtensions.valueMapper(IEnumerable`1 properties, IExtendedProperty value)
   at OSPSuite.Core.Domain.Data.DataRepositoryExtensions.<>c__DisplayClass2_0.<IntersectingMetaData>b__3(IExtendedProperty x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.editObservedData(IEnumerable`1 observedData, IEnumerable`1 rules)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryMetaDataPresenter.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.<>c__DisplayClass8_0.<Edit>b__0(IDataRepositoryItemPresenter presenter)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ObservedData.EditDataRepositoryPresenter.Edit(DataRepository repositoryToEdit)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\SW-Dev\PK-Sim\branches\10.0\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 44
   at PKSim.Presentation.UICommands.EditSubjectUICommand`1.PerformExecute() in C:\SW-Dev\PK-Sim\branches\10.0\src\PKSim.Presentation\UICommands\EditSubjectUICommand.cs:line 19
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by abdelr** [comment]
Different effect but same cause. Closing the issue in favor of #1221.
