### ISSUE TITLE
ConcurrentRunSimulationBatch should throw when being created with wrong paths

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1346]
If a `ConcurrentRunSimulationBatch` is created with `ConcurrentRunSimulationBatch` that contain paths to molecules or parameters that are not in the simulation, it should throw an error. Currently, it is created and throws an error when trying to simulate: (code in R:)

```
simb <- ospsuite::loadSimulation(filePath = "ssapp.pkml")
sb <- ospsuite::createSimulationBatch(simulation = simb, parametersOrPaths = "lol")
sb$addRunValues(parameterValues = 1)
res <- ospsuite::runSimulationBatches(simulationBatches = sb)

Error in rClr::clrCall(simulationRunner, "RunConcurrently") : 
  Type:    System.ArgumentOutOfRangeException
Message: Specified argument was out of the range of valid values.
Parameter name: index
Method:  TSource ElementAt[TSource](System.Collections.Generic.IEnumerable`1[TSource], Int32)
Stack trace:
   at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at OSPSuite.R.Services.ConcurrentSimulationRunner.<>c__DisplayClass14_0.<RunConcurrentlyAsync>b__4(SimulationBatchRunValues rv, Int32 i)
   at System.Linq.Enumerable.<SelectIterator>d__5`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.R.Services.ConcurrentSimulationRunner.<RunConcurrentlyAsync>d__14.MoveNext()
```

**Comment by PavelBal** [comment]
Ok may well be. Let's keep this issue open though to check when the other one is fixed.

**Comment by msevestre** [comment]
@PavelBal CAn you check if this is fixed? If yes, please close:)

**Comment by PavelBal** [comment]
This is not fixed.

**Comment by Yuri05** [comment]
@PavelBal Still an issue?

**Comment by PavelBal** [comment]
Yes
