### ISSUE TITLE
New data import does not accept "1/ml" as unit for arithmetic standard deviation

### ISSUE THREAD

**Issue by Christoph27** [Open-Systems-Pharmacology/OSPSuite.Core#1419]
Steps to reproduce: Trying to import data from attached Excel file.

Time assign to column "Time [h]"
Measurement assign to column "Tumor (Conc) [1/ml]" ->  select Dimension: "inversed volume", Unit: "1/ml"
Error assign to column "Error(Arithm) Tumor [1/ml]" -> select Error type: "Arithmetic Standard Deviation", Unit: "1/ml"

Then there is a red error sign for the Error column stating that "Field must contain a valid unit description" (see screenshot)

Why is there anything not valid?

[test_ErrorInvTime.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7808474/test_ErrorInvTime.xlsx)

<img width="832" alt="ErrorInvTime" src="https://user-images.githubusercontent.com/26439150/148079803-0fd6ebe7-b469-4bc3-929f-de207dea6386.png">

**Comment by Yuri05** [comment]
@Christoph27 Is this still the case with the 11.1 beta-version?

**Comment by Christoph27** [comment]
It still does not work but the behavior is different: Now I can assign all columns. When trying to import I get the Error:

Application:
MoBi® 11.1.96

Don't know how to build curve binder for 'Invalid'

Stack trace:
```
at OSPSuite.UI.Services.CurveBinderFactory.CreateFor(Curve curve, Object chartControl, CurveChart chart, IAxisBinder yAxisBinder)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.getOrCreateCurveBinderFor(Curve curve)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.refreshCurveBinderFor(Curve curve)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.updateCurves()
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.updateChart()
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.Edit(CurveChart chart, ChartFontAndSizeSettings displayChartFontAndSizeSettings)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.Edit(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.bindToChart()
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.PlotObservedData(IEnumerable`1 observedData)
   at OSPSuite.Presentation.Presenters.Charts.SimpleChartPresenter.PlotObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.plotObservedData(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.ObservedData.DataRepositoryChartPresenter.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.PlotDataRepository(DataRepository dataRepository)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.plotDataSet(Object sender, DataSetSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.DataSetSelected(Int32 index)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.onDataSetNameSelected(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
When following the exact steps described, creating the following mapping:
![image](https://user-images.githubusercontent.com/37107428/208073963-530e7d4a-d47c-4092-882b-9c6396e5fac0.png)

I can import the data without errors:
![image](https://user-images.githubusercontent.com/37107428/208074049-73b5350d-78b8-4b52-9b07-11ceb9e9320a.png)

So I would say from my side I cannot reproduce.

**Comment by Christoph27** [comment]
I re-tried and here is how I got the error above:
If you do the matching to the table columns, the mapping of the "Error" looks like this

<img width="248" alt="image" src="https://user-images.githubusercontent.com/26439150/208084827-b651f3b3-706c-4fae-a01f-2f7f4e99cde2.png">

If you then try to import the data,  you get the error above. 
If you instead (before trying to import) just click on the field "Error/Edit Extra Fields" and hit return, the arithmetic standard deviation information is added and everything works as you described.
It seems that I was a little impatient when testing but the error message could be more clear to the user ...

**Comment by PavelBal** [comment]
There is no bug as I see it, but the message `Field must contain a valid unit description` does not help the user.

"Unit settings could not be set, please adjust" or somthing like this.

**Comment by Christoph27** [comment]
There was a bug before with the error message "Field must contain a valid unit description" when I reported it a year ago. The error message is in principle useful  but was not matching to the situation. This bug was fixed meanwhile. When testing if the bug was fixed few weeks ago, I did it rather quickly and stayed with the "default" mapping you can see in my last comment. When trying to import, I got the error "Don't know how to build curve binder for 'Invalid'". This message is not useful to the user....

**Comment by georgeDaskalakis** [comment]
From the coversation I would say the issue is resolved. I will close for now. If there are any objections feel free to reopen :)
