### ISSUE TITLE
Importer: Error importing in MoBi

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#1438]
[CompiledDataSet.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7846552/CompiledDataSet.xlsx)

[esqlabs_dataImporter_configuration.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7846554/esqlabs_dataImporter_configuration.zip)

This file (close the sheet "MetaData") plus this configuration -> "Load all sheets" = Error

Application:
MoBi® 10.0.122

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.<>c__DisplayClass22_0.<Parse>b__1(DataFormatParameter p)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.buildDataSetsRecursively(IUnformattedData data, IEnumerable`1 parameters, Stack`1 indexes, List`1 dataSets, IReadOnlyList`1 columnInfos)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.buildDataSets(IUnformattedData data, IEnumerable`1 parameters, IReadOnlyList`1 columnInfos)
   at OSPSuite.Infrastructure.Import.Core.DataFormat.AbstractColumnsDataFormat.Parse(IUnformattedData data, IReadOnlyList`1 columnInfos)
   at OSPSuite.Infrastructure.Import.Services.Importer.AddFromFile(IDataFormat format, Cache`2 dataSheets, IReadOnlyList`1 columnInfos, IDataSource alreadyExisting)
   at OSPSuite.Infrastructure.Import.Core.DataSource.AddSheets(Cache`2 dataSheets, IReadOnlyList`1 columnInfos, String filter)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheets(IDataSourceFile dataSourceFile, Cache`2 sheets, String filter, String selectedNamingConvention)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.loadSheetsFromDataPresenter(Object sender, ImportSheetsEventArgs args)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.ImportDataForConfirmation()
   at OSPSuite.UI.Views.Importer.ImporterDataView.onButtonImportAllClicked(Object sender, EventArgs e)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
Not reproducible in develop anzmore, probably solved by #1441
