### ISSUE TITLE
Trying to import ontogeny values from PK-Sim => Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#1444]
Load the attach file in PKSim v11 with the following settings
![image](https://user-images.githubusercontent.com/1041237/149320110-d3124df7-b689-4bf2-8037-dbc6a73c3e99.png)
[Ontogeny.xlsx](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/7862258/Ontogeny.xlsx)

Application:
PK-Sim® 11.0.0

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.convertParsedDataColumnAndReturnWarningFlag(DataRepository dataRepository, KeyValuePair`2 columnAndData, String fileName)
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.ConvertImportDataSet(ImportedDataSet dataSet)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.plotDataSet(Object sender, DataSetSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.DataSetSelected(Int32 index)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.onDataSetNameSelected(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

Also: The title says "Import Observed Data" 
It used to say I believe Import Ontogeny or sthg like this...

**Comment by msevestre** [comment]
I do not know if the bug occurs also in v10..

**Comment by msevestre** [comment]
This works in v10.
