### ISSUE TITLE
Error when loading a file

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1481]
Playing around with the dataset from https://github.com/Open-Systems-Pharmacology/MoBi/issues/685#issuecomment-1029993010 I got the following issue:

I created the mapping/filtering as described in the original issue and saved my importer configuration: [Config01_withFilter.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/8014179/Config01_withFilter.zip)

Next time when I opened the same file for import and selected "Load Configuration", I got the warning below:
![grafik](https://user-images.githubusercontent.com/25061876/152766112-cd92f695-5f9d-4157-b308-08cdec8fb4a7.png)

I said "Yes" in the warning. The configuration was loaded then and my mapping looked as before, so everything seemed OK.
Not sure why the warning came though.

**Comment by georgeDaskalakis** [comment]
I cannot reproduce in the current Core develop. I also remember fixing this, but do not seem to be able to find the issue number...

**Comment by PavelBal** [comment]
Also cannot reproduce. @Yuri05 Could you check and close the issue, if fixed?

**Comment by Yuri05** [comment]
I could not reproduce the issue anymore (PK-Sim 11.1.110).
However, after loading the configuration and clicking on "Add All Sheets" I get the exception below:

```
Application:
PK-Sim® 11.1.110

An item with the key 'Dose' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.ConvertImportDataSet(ImportedDataSet dataSet)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.plotDataSet(Object sender, DataSetSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.DataSetSelected(Int32 index)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.onDataSetNameSelected(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
@Yuri05 this occurs because the configuration file (.xml) contains a duplication of the Dose mapping:

![image](https://user-images.githubusercontent.com/37107428/210958421-b2246b3a-d702-4723-8d20-07e8ef7aaf9e.png)

Tbh I have no clue how this duplication came to exist...I tried to recreating following the steps from the other error, but couldn't. I would suggest we consider this solved as long as we cannot reproduce from the beginning - the configuration definately comes from an older version of the importer.

**Comment by Yuri05** [comment]
yep, the configuration file was saved a while.
So I retried with PK-Sim 11.1.118

csv-file from https://github.com/Open-Systems-Pharmacology/MoBi/issues/685 (https://github.com/Open-Systems-Pharmacology/MoBi/files/7996526/testcsv.csv)

Configuration: s. below.
Also resaved it with PK-Sim 11.1.118: [Config_testcsv.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/10362622/Config_testcsv.zip)

![grafik](https://user-images.githubusercontent.com/25061876/211086669-4fd33c58-a8d3-4001-802f-aed8bc24779f.png)

When I click on "Add current sheet" I get the error message below.
```
Application:
PK-Sim® 11.1.118

An item with the key 'Dose' has already been added
-----------------------------------------------------
An item with the same key has already been added.

Stack trace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
 --- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Infrastructure.Import.Core.Mappers.DataSetToDataRepositoryMapper.ConvertImportDataSet(ImportedDataSet dataSet)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.plotDataSet(Object sender, DataSetSelectedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.DataSetSelected(Int32 index)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.onDataSetNameSelected(Object sender, EventArgs eventArgs)
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass26_0`1.<OnEvent>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by PavelBal** [comment]
@georgeDaskalakis

**Comment by georgeDaskalakis** [comment]
@Yuri05 the question is what where the steps to reproduce the configuration. Because this is where the error is, not in loading it. If you want we can have a call about this today.

**Comment by PavelBal** [comment]
@georgeDaskalakis Yuri tried to import the file freshly without using a configuration.

**Comment by Yuri05** [comment]
>Yuri tried to import the file freshly without using a configuration.

correct. If I set mapping/filters as shown in the screenshot above, the error comes.
And to reproduce the configuration: just set all mapping/filters as shown in the screenshot above and save the configuration
