### ISSUE TITLE
Saving a project in PKSim with Parameter Identification => Crash

### ISSUE THREAD

**Issue by abdelr** [Open-Systems-Pharmacology/OSPSuite.Core#1488]
@msevestre commented on [Fri Jan 14 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2050)

Application:
PK-Sim® 11.0.0

Unable to cast object of type 'OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationFeedback' to type 'OSPSuite.Core.Domain.IWithId'.

Stack trace:
```
at OSPSuite.Utility.Extensions.ConversionExtensions.DowncastTo[T](Object objectToCast)
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.createNewWorkspaceLayoutWithOpenPresenters() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 70
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.SaveCurrentLayout() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 50
   at PKSim.Presentation.Services.ProjectTask.saveProjectToFile(String fileName) in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 181
   at PKSim.Presentation.Services.ProjectTask.SaveCurrentProject() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 130
   at PKSim.Presentation.UICommands.SaveProjectCommand.Execute() in C:\dev\PK-Sim\src\PKSim.Presentation\UICommands\SaveProjectCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

---

@msevestre commented on [Fri Jan 14 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2050#issuecomment-1013206338)

Due to new addition of PIFeedback object.. should probably not be saved in layout.

---

@msevestre commented on [Wed Feb 09 2022](https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/2050#issuecomment-1033779751)

@abdelr This needs to be fixed to

**Comment by msevestre** [comment]
I don't think the fix proposed is what needs to be done. PKSim will try to load a view for this is that does not exist.
Rather, the line in PKSim casting ti IWithId should be changed

https://github.com/Open-Systems-Pharmacology/PK-Sim/blob/develop/src/PKSim.Presentation/Services/WorkspaceLayoutUpdater.cs#L70

**Comment by abdelr** [comment]
Moving back to PKSim
