### ISSUE TITLE
Error message when opening the project

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#1673]
When opening the project attached, the error message below comes. [Erythromycin-Model_2.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/9218761/Erythromycin-Model_2.zip)

After that the project is opened and all objects (BBs/Simulations) seems to be there, and the Working Journal is assigned as well

```
Application:
PK-Sim® 11.0.150

Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Presentation.Presenters.Diagram.BaseDiagramPresenter`3.Refresh()
   at OSPSuite.Presentation.Presenters.Journal.JournalDiagramPresenter.Handle(JournalPageUpdatedEvent eventToHandle)
   at OSPSuite.Utility.Events.EventPublisher.<>c__DisplayClass4_1`1.<PublishEvent>b__1()
   at OSPSuite.Utility.Exceptions.ExceptionManagerBase.Execute(Action action)
```

**Comment by msevestre** [comment]
It seems that if the view is opened, an event is sometimes triggered before the model is loaded.
