### ISSUE TITLE
Observed data import crash

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2067]
[BugImport.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/12260379/BugImport.zip)
1. Open attached project **bugImport.pksim5** in PK-Sim
2. Select `Observed Data ➡️  Add Observed Data for ➡️ C1`
3. Select attached file **NEW3.csv**
4. Keep the proposed column separator (comma)
5. In the data import: Load configuration from the attached file **NEW3.xml**
6. Click on "Add current sheet"

The error message below comes.

```
Application:
PK-Sim® 11.2.142

Specified argument was out of the range of valid values.
Parameter name: index

Stack trace:

at System.Linq.Enumerable.ElementAt[TSource](IEnumerable`1 source, Int32 index)
   at OSPSuite.Infrastructure.Import.Core.ParsedDataSet.NameFromConvention(IReadOnlyList`1 mappings, String convention, String fileName, String sheetName)
   at OSPSuite.Infrastructure.Import.Services.Importer.<>c__DisplayClass9_1.<NamesFromConvention>b__1(ParsedDataSet s)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Infrastructure.Import.Services.Importer.NamesFromConvention(String namingConvention, String fileName, Cache`2 dataSets, IReadOnlyList`1 mappings)
   at OSPSuite.Infrastructure.Import.Core.DataSource.NamesFromConvention()
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.<>c__DisplayClass15_0.<.ctor>b__2(Object s, NamingConventionChangedEventArgs a)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.ImportConfirmationPresenter.TriggerNamingConventionChanged(String namingConvention)
   at OSPSuite.UI.Views.Importer.ImportConfirmationView.<onNamingConventionChanged>b__16_0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

The problem seems to be that the user somehow managed to create an invalid importer configuration.
After the loading of the configuration, it looks like this:
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/1c2e2b35-616a-4149-960d-19942b69d8aa)

But when I click on the measurement unit: I see an empty mapped unit column instead of the selected unit [µg/l]
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/4fa42da4-6269-48cb-8cd4-28117daee4a2)

I did not manage to fix this wrong configuration. Only if I close the importer, reopen it and map all columns/units manually again, I can import.

**Comment by Yuri05** [comment]
@georgeDaskalakis OK, one possible scenario to reproduce - if we have an excel column named as our compound
[NEW3.csv](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/12261093/NEW3.csv)

1. I import into the project from the issue description, but not for a compound, just 
2. I map any of the columns (not the molecule) to the Excel column C1
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/381d487a-c333-470d-a9a0-4950d066da53)
3. I map molecule to C1
![grafik](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25061876/e79726b3-16bf-4375-95c9-2af48ad432f7)

Now I am in the invalid state. If I finish to map the remaining columns (time/measurement/...) and try to import - I get the error from the issue.

Still not what the user did, though (he did not have such a situation). 
But at least a way to reproduce :)
