### ISSUE TITLE
error when trying to export to excel

### ISSUE THREAD

**Issue by Fate-afshar** [Open-Systems-Pharmacology/OSPSuite.Core#2094]
Dear all,
I've been having some trouble trying to export my project to excel . when I click on my desired chart it gives an error exclaiming : 

The workbook already contains a sheet named 'actual time.Sheet1.vancomycin_10'

Stack trace:
```
at NPOI.XSSF.UserModel.XSSFWorkbook.ValidateSheetName(String sheetName)
   at NPOI.XSSF.UserModel.XSSFWorkbook.CreateSheet(String sheetname)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.exportDataTableToWorkBook(IWorkbookConfiguration workBookConfiguration, DataTable dataTable)
   at OSPSuite.Infrastructure.Export.ExportToExcelTask.ExportDataTablesToExcel(IEnumerable`1 dataTables, String fileName, Boolean openExcel, IWorkbookConfiguration workBookConfiguration)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataTables, String fileName, Boolean launchExcel)
   at OSPSuite.Infrastructure.Export.DataRepositoryExportTask.ExportToExcel(IEnumerable`1 dataColumns, String fileName, Boolean launchExcel, DataColumnExportOptions exportOptions)
   at OSPSuite.Core.Services.CurveChartExportTask.ExportToExcel(CurveChart chart)
   at OSPSuite.Presentation.Presenters.Charts.ChartDisplayPresenter.ExportToExcel()
   at OSPSuite.Presentation.MenuAndBars.ExecuteActionUICommand.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

I'd appreciate your help
thank you

**Comment by msevestre** [comment]
Ok this is because there is a limit of number of characters that one can have for a sheetname
