### ISSUE TITLE
Data importer: error when "Reload under the same settings"

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2176]
[core-reload-with-same-settings.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/13513555/core-reload-with-same-settings.zip)

1. Load the attached excel file with the attached importer configuration -> One data set "Laskin 1982.Group A__1_Human_PeripheralVenousBlood_Plasma_2.5 mg/kg_iv_" is added
2. Open the excel file, and add a new row where the "Molecule" column is populated with any value:

![image](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/assets/25903040/4feb546f-d6e3-43d6-b1ac-d6f3aec78906)

3. Select "Reload under the same settings" for the imported data set and select the excel file.

Application:
PK-Sim® 12.0.117

Key 'Molecule' could not be found

Stack trace:
```
at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__11_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass6_0.<AreFromSameMetaDataCombination>b__0(KeyValuePair`2 keyValuePair)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Presentation.Services.DataImporter.AreFromSameMetaDataCombination(DataRepository sourceDataRepository, DataRepository targetDataRepository)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass7_0.<repositoryExistsInList>b__0(DataRepository dataRepo)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Presentation.Services.DataImporter.repositoryExistsInList(IEnumerable`1 dataRepositoryList, DataRepository targetDataRepository)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass5_0.<CalculateReloadDataSetsFromConfiguration>b__0(DataRepository dataSet)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Services.DataImporter.CalculateReloadDataSetsFromConfiguration(IReadOnlyList`1 dataSetsToImport, IReadOnlyList`1 existingDataSets)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddAndReplaceObservedDataFromConfigurationToProject(ImporterConfiguration configuration, IEnumerable`1 observedDataFromSameFile)
   at PKSim.Presentation.UICommands.ReloadAllObservedDataCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by PavelBal** [comment]
I believe it should. When I first imported the file, the configuration contained grouping by the "Molecule" column, the column was just empty. I expect that the importer reads the file using the *same configuration* as during the first import.

**Comment by PavelBal** [comment]
@Yuri05 @rwmcintosh I vote for this to be in V12 because this is SUUUUPER ANNOYING!
