### ISSUE TITLE
Observed data - reload under the same settings -> Error in PI

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite.Core#2179]
Whe using the funtion to "Reload under the same settings", and the updated data set has less values that the previous one and it was used in a PI, trying to open the PI:

Application:
MoBi® 11.2.138

Values.Length = 154 != 67 = BaseGrid.Count

Stack trace:
```
at OSPSuite.Core.Domain.Data.DataColumn.set_Values(IReadOnlyList`1 value)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.createWeightColumn(BaseGrid baseGrid, WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.MapFrom(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.MapDataTableFromColumns()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.Rebind()
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.EditObservedData(DataRepository observedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.EditObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataPresenter.Edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.edit(WeightedObservedData weightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.AddObservedData(WeightedObservedData weightedObservedData)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.<>c__DisplayClass10_0.<addWeightedObservedDataToView>b__0()
   at OSPSuite.Utility.Extensions.LatchableExtensions.DoWithinLatch(ILatchable latchable, Action action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.addWeightedObservedDataToView(List`1 allWeightedObservedData)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.<>c__DisplayClass2_0.<InitializeSubPresentersWith>b__0(IParameterIdentificationItemPresenter x)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.InitializeSubPresentersWith(ParameterIdentification parameterIdentification)
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable)
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit)
   at MoBi.Presentation.Tasks.SingleStartPresenterTask.StartForSubject[T](T subject)
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

**Comment by rwmcintosh** [comment]
The right fix might be to prevent reload don't you think? Because here we have created a weighting for 154 measurements and the new observed data only contains 67. Which weights do you throw out?

**Comment by rwmcintosh** [comment]
[test.zip](https://github.com/user-attachments/files/18442411/test.zip)

[Human.Plasma.IV.Subj 1.xlsx](https://github.com/user-attachments/files/18442413/Human.Plasma.IV.Subj.1.xlsx)
