### ISSUE TITLE
V12: Error when Updating a simulation from BBs

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#2342]
[02_TableFormulation_NoSuspension.zip](https://github.com/user-attachments/files/17118131/02_TableFormulation_NoSuspension.zip)
In the project attached: try to update the simulation **11.3_S2_NoSuspension** from Building blocks.

```
Application:
MoBi® 12.0.0

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Core.Domain.Services.ModelValidator.CheckFormulaIn(IUsingFormula entity, IFormula formulaToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ModelValidator.CheckReferences(IUsingFormula usingFormulaToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ModelValidator.CheckParameter(IParameter parameterToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ValidatorForQuantities.Visit(IParameter parameter)
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Core.Domain.ObjectBase.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Model.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Services.ModelValidator.Validate(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validate[TValidationVisitor](ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validateModel(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(SimulationConfiguration simulationConfiguration, String modelName)
   at MoBi.Core.Domain.Services.SimulationFactory.createModel(SimulationConfiguration simulationConfiguration, String name) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Domain\Services\SimulationFactory.cs:line 120
   at MoBi.Core.Domain.Services.SimulationFactory.<>c__DisplayClass14_0.<CreateModelAndValidate>b__0() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Domain\Services\SimulationFactory.cs:line 101
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by rwmcintosh** [comment]
@Yuri05 that seems like the error happened trying to restore the state of the building blocks when rolling back those commands. Do you happen to have a version of this from before these changes?

**Comment by Yuri05** [comment]
[01.zip](https://github.com/user-attachments/files/17479934/01.zip)
OK, with this project reproducible.

<details><summary><b>Steps to reproduce</b></summary>

1. In the Events-BB: go to the **Fraction (dose)** parameter in the **ProtocolSchemaItem** container. Its formula is set to some _TableFormulaWithOffset_
![grafik](https://github.com/user-attachments/assets/37b2603b-82da-4126-85fb-68801042a189)
2. Change formula type to **Table** and select **Fraction (dose)** formula
![grafik](https://github.com/user-attachments/assets/506427b4-d25a-40d5-87fa-03befb10bcbc)
3. Update the simulation from building blocks.
4. In the history, rollback to the state before changing the formula
![grafik](https://github.com/user-attachments/assets/ee78138a-e277-4fb2-a8dc-a3b36155fdb9)
![grafik](https://github.com/user-attachments/assets/40597af3-229c-4569-b3ac-f175b07373ba)
5. Update the simulation from building blocks again

```
Application:
MoBi® 12.0.0

Exception has been thrown by the target of an invocation.
-----------------------------------------------------
Object reference not set to an instance of an object.

Stack trace:

at OSPSuite.Core.Domain.Services.ModelValidator.CheckFormulaIn(IUsingFormula entity, IFormula formulaToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ModelValidator.CheckReferences(IUsingFormula usingFormulaToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ModelValidator.CheckParameter(IParameter parameterToCheck, ResolveErrorBehavior resolveErrorBehavior)
   at OSPSuite.Core.Domain.Services.ValidatorForQuantities.Visit(IParameter parameter)
 --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at OSPSuite.Utility.Visitor.VisitorInvoker.invokeVisitMethod[T](IVisitor visitor, T objectToVisit, MethodInfo method)
   at OSPSuite.Utility.Visitor.VisitorInvoker.InvokeVisit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Utility.Visitor.VisitorExtensions.Visit[T](IVisitor visitor, T objectToVisit)
   at OSPSuite.Core.Domain.ObjectBase.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Container.<>c__DisplayClass22_0.<AcceptVisitor>b__0(IEntity child)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Core.Domain.Container.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Model.AcceptVisitor(IVisitor visitor)
   at OSPSuite.Core.Domain.Services.ModelValidator.Validate(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validate[TValidationVisitor](ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validateModel(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(SimulationConfiguration simulationConfiguration, String modelName)
   at MoBi.Core.Domain.Services.SimulationFactory.createModel(SimulationConfiguration simulationConfiguration, String name) in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Domain\Services\SimulationFactory.cs:line 120
   at MoBi.Core.Domain.Services.SimulationFactory.<>c__DisplayClass14_0.<CreateModelAndValidate>b__0() in C:\SW-Dev\MoBi\branches\11.0\src\MoBi.Core\Domain\Services\SimulationFactory.cs:line 101
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

</details>

**Comment by rwmcintosh** [comment]
@benjaperez1983  ^^^
