### ISSUE TITLE
Validation of simulation fails if the same object fails validation in two different ways

### ISSUE THREAD

**Issue by rwmcintosh** [Open-Systems-Pharmacology/OSPSuite.Core#2365]
@PavelBal has shared a project with me directly.

The model has errors, and rightly fails validation. But different validation algorithms have flagged the same object (a reaction in this case) as the culprit and when the messages are combined, the caching mechanism fails because the same key is added more than once.

**Comment by rwmcintosh** [comment]
```
An item with the same key has already been added.
 
Stack trace:

at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
--- End of inner exception stack trace ---
   at OSPSuite.Utility.Collections.Cache`2.Add(TKey key, TValue value)
   at OSPSuite.Utility.Collections.Cache`2.Add(TValue value)
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action)
   at OSPSuite.Utility.Collections.Cache`2.AddRange(IEnumerable`1 range)
   at OSPSuite.Core.Domain.ValidationResult..ctor(IEnumerable`1 messages)
   at OSPSuite.Core.Domain.ValidationResult..ctor(ValidationResult[] validationResults)
   at OSPSuite.Core.Domain.Services.ModelConstructor.validateModel(ModelConfiguration modelConfiguration)
   at OSPSuite.Core.Domain.Services.ModelConstructor.CreateModelFrom(SimulationConfiguration simulationConfiguration, String modelName)
   at MoBi.Core.Domain.Services.SimulationFactory.createModel(SimulationConfiguration simulationConfiguration, String name)
   at MoBi.Core.Domain.Services.SimulationFactory.<>c__DisplayClass14_0.<CreateModelAndValidate>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

```
