### ISSUE TITLE
Exception when loading a PI only from Journal (without matching obs data and sim). Should not crash instead

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#350]
Application:
PK-Sim® 7.3.0 - Build 0

Value cannot be null.
Parameter name: source

Stack trace:
```
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Mappers.ParameterIdentifications.WeightedDataRepositoryToDataTableMapper.MapFrom(WeightedObservedData weightedObservedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Mappers\ParameterIdentifications\WeightedDataRepositoryToDataTableMapper.cs:line 30
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.MapDataTableFromColumns(IEnumerable`1 dataColumns) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\WeightedDataRepositoryDataPresenter.cs:line 35
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.Rebind() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ObservedData\BaseDataRepositoryDataPresenter.cs:line 63
   at OSPSuite.Presentation.Presenters.ObservedData.BaseDataRepositoryDataPresenter`2.EditObservedData(DataRepository observedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ObservedData\BaseDataRepositoryDataPresenter.cs:line 58
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.WeightedDataRepositoryDataPresenter.EditObservedData(WeightedObservedData weightedObservedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\WeightedDataRepositoryDataPresenter.cs:line 41
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataPresenter.Edit(WeightedObservedData weightedObservedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationWeightedObservedDataPresenter.cs:line 35
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.edit(WeightedObservedData weightedObservedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationWeightedObservedDataCollectorPresenter.cs:line 118
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.SelectObservedData(WeightedObservedData weightedObservedData) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationWeightedObservedDataCollectorPresenter.cs:line 76
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationWeightedObservedDataCollectorPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationWeightedObservedDataCollectorPresenter.cs:line 45
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationDataSelectionPresenter.EditParameterIdentification(ParameterIdentification parameterIdentification) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationDataSelectionPresenter.cs:line 90
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.<>c__DisplayClass2_0.<InitializeSubPresentersWith>b__0(IParameterIdentificationItemPresenter x) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\EditParameterIdentificationPresenter.cs:line 42
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Extensions\EnumerableExtensions.cs:line 36
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.EditParameterIdentificationPresenter.InitializeSubPresentersWith(ParameterIdentification parameterIdentification) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\EditParameterIdentificationPresenter.cs:line 42
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\EditAnalyzablePresenter.cs:line 77
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\SubjectPresenter.cs:line 18
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\projects\PK-Sim\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 43
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\EditParameterIdentificationUICommand.cs:line 17
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\ObjectUICommands.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\UICommandExtensions.cs:line 26
```

**Comment by msevestre** [comment]
Relates to #240
