### ISSUE TITLE
PI Corrupted when referencing a process parameter that is removed from the simulation

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite.Core#497]
see https://github.com/Open-Systems-Pharmacology/PK-Sim/issues/1109

**Comment by msevestre** [comment]
This is actually happening when loading the snapshot

Steps to reproduce:
1. Load project 497 in PKSim
2. Configure Simulation and change process from proc1 to proc2
![image](https://user-images.githubusercontent.com/1041237/53272383-175af080-36bf-11e9-8916-dbd0a990a0d7.png)
3. Export to snapshot
4. Load from snapshot

```
Information: Loading Project from snapshot file 'C:\tests\github\497-corrupt.json'
Error: Object reference not set to an instance of an object.

For more information or questions, please visit the Open Systems Pharmacology Forum (forum.open-systems-pharmacology.org).

Stack trace:
at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.<>c.<ensureThatDimensionsAreEqual>b__8_0(IParameter x) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\IdentificationParameterFactory.cs:line 75
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__64`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.ensureThatDimensionsAreEqual(IEnumerable`1 parameters) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\IdentificationParameterFactory.cs:line 75
   at OSPSuite.Core.Domain.Services.ParameterIdentifications.IdentificationParameterFactory.CreateFor(IEnumerable`1 parameterSelections, ParameterIdentification parameterIdentification) in C:\projects\ospsuite-core\src\OSPSuite.Core\Domain\Services\ParameterIdentifications\IdentificationParameterFactory.cs:line 40
   at PKSim.Core.Snapshots.Mappers.IdentificationParameterMapper.<MapToModel>d__6.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\IdentificationParameterMapper.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBaseExtensions.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ParameterIdentificationMapper.<MapToModel>d__8.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\ParameterIdentificationMapper.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBaseExtensions.cs:line 93
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\ProjectMapper.cs:line 106
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBase`2.<MapToModel>d__1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Mappers\SnapshotMapperBase.cs:line 17
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<loadModelsFromSnapshots>d__16`1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 155
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadModelsFromSnapshotFile>d__15`1.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 146
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotFile>d__17.MoveNext() in C:\projects\PK-Sim\src\PKSim.Core\Snapshots\Services\SnapshotTask.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadProjectFromSnapshotPresenter.cs:line 51
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<PerformLoad>d__19.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadFromSnapshotPresenter.cs:line 125
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<Start>d__14.MoveNext() in C:\projects\PK-Sim\src\PKSim.Presentation\Presenters\Snapshots\LoadFromSnapshotPresenter.cs:line 105
```

**Comment by msevestre** [comment]
if you do it in PKSim, the PI opens and shows an invalid object
![image](https://user-images.githubusercontent.com/1041237/53272464-6143d680-36bf-11e9-9bf1-a84c8bfb37bb.png)

Snapshot is not so resilient however!

@teutonicod: In order to understand what's going on with your project, I would need to actually get it.
But this is exactly the error you are getting so we are pretty close

In short: Don't remove a parameter from a simulation that is also used in a PI :)

**Comment by msevestre** [comment]
The other error is probably similar. A paramter is used in a plot (VPC) that does not exist anymore in the simulation. That should also be checked...

**Comment by msevestre** [comment]
Yep could reproduce your issue
Application:
PK-Sim® 7.5.0.0

Object reference not set to an instance of an object.

Stack trace:
```
at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.confidenceIntervalDTOFrom(ICache`2 confidenceInterval, IdentificationParameter identificationParameter, OptimizedParameterValue optimizedParameter) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationConfidenceIntervalPresenter.cs:line 54
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.<>c__DisplayClass3_0.<mapFrom>b__2(<>f__AnonymousType0`2 <>h__TransparentIdentifier0) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationConfidenceIntervalPresenter.cs:line 47
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationConfidenceIntervalPresenter.CalculateConfidenceIntervalFor(ParameterIdentification parameterIdentification, ParameterIdentificationRunResult runResult) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationConfidenceIntervalPresenter.cs:line 34
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationCovarianceAnalysisPresenter.UpdateAnalysis() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationCovarianceAnalysisPresenter.cs:line 40
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.set_SelectedRunResults(ParameterIdentificationRunResult value) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationMatrixAnalysisPresenter.cs:line 95
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.UpdateAnalysisBasedOn(IAnalysable analysable) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationMatrixAnalysisPresenter.cs:line 84
   at OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationMatrixAnalysisPresenter`1.InitializeAnalysis(ISimulationAnalysis simulationAnalysis, IAnalysable analysable) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\ParameterIdentifications\ParameterIdentificationMatrixAnalysisPresenter.cs:line 42
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.createAnalysis(ISimulationAnalysis simulationAnalysis) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\EditAnalyzablePresenter.cs:line 131
   at OSPSuite.Utility.Extensions.EnumerableExtensions.Each[T](IEnumerable`1 list, Action`1 action) in C:\projects\ospsuite-utility\src\OSPSuite.Utility\Extensions\EnumerableExtensions.cs:line 36
   at OSPSuite.Presentation.Presenters.EditAnalyzablePresenter`4.Edit(TAnalyzable analyzable) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\EditAnalyzablePresenter.cs:line 79
   at OSPSuite.Presentation.Presenters.SubjectPresenter`3.Edit(Object objectToEdit) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\Presenters\SubjectPresenter.cs:line 18
   at PKSim.Presentation.Core.SingleStartPresenterTask.StartForSubject[T](T subject) in C:\projects\PK-Sim\src\PKSim.Presentation\Core\SingleStartPresenterTask.cs:line 43
   at OSPSuite.Presentation.UICommands.EditParameterIdentificationUICommand.PerformExecute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\EditParameterIdentificationUICommand.cs:line 17
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute() in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\ObjectUICommands.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator) in C:\projects\ospsuite-core\src\OSPSuite.Presentation\UICommands\UICommandExtensions.cs:line 26
```

**Comment by Yuri05** [comment]
@msevestre Is this really fixed? Following the steps you described [above](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/497#issuecomment-466554873) I still get a crash when importing from snapshot in PK-Sim 9.

<details><summary>Error importing from snapshot</summary>

```
Information: Loading Project from snapshot file 'C:\00000_Verifications\17\497.json'
Error: Object reference not set to an instance of an object.

Stack trace:
at PKSim.Core.Snapshots.Mappers.ObjectBaseSnapshotMapperBase`2.MapSnapshotPropertiesToModel(TSnapshot snapshot, TModel model)
   at PKSim.Core.Snapshots.Mappers.IdentificationParameterMapper.<MapToModel>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ParameterIdentificationMapper.<MapToModel>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBaseExtensions.<MapTo>d__9`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.ProjectMapper.<MapToModel>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Mappers.SnapshotMapperBase`2.<MapToModel>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<loadModelsFromSnapshots>d__16`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadModelsFromSnapshotFile>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Core.Snapshots.Services.SnapshotTask.<LoadProjectFromSnapshotFile>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadProjectFromSnapshotPresenter.<LoadModelAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<PerformLoad>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at PKSim.Presentation.Presenters.Snapshots.LoadFromSnapshotPresenter`1.<Start>d__14.MoveNext()
```
</details>

**Comment by msevestre** [comment]
Well if you are getting the issue, then it's not fixed :)

**Comment by msevestre** [comment]
Yep crash in PKSim indeed. But not the same error. 
I though it would be caught but no

**Comment by msevestre** [comment]
checking this now

**Comment by msevestre** [comment]
This is fixed
Here is the error message
```
Information: Loading Project from snapshot file 'C:\tests\10.0\497\497.json'
Warning: Cannot create identification parameter 'S|Comp-Total Hepatic Clearance-Proc1|Specific clearance' for parameter identification 'Parameter Identification 1'.
Information: Project loaded from snapshot
```
