### ISSUE TITLE
Sum Formula references are duplicated

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/OSPSuite.Core#572]
While testing MoBi Beta 8.0.6, issue #539:

See the attached project below, where I used the ManualModel and added sum formula parameters to the containers Vial1 and Vial2. In simulation S2, only sums of molecules B and C concentrations are calculated. It all works, giving the same result as the corresponding "SumMetabolites" observers. The text export (also attached as S2.txt), however, shows duplicate references for each of the summands:

Parameter: S2|BigVial|Vial1|SumMetab
	IsFixed: False
	Value: 0 [µmol/l]
	Formula: P_1 + P_2
		P_1: S2|BigVial|Vial1|B|Concentration(0 [µmol/l])
		P_2: S2|BigVial|Vial1|C|Concentration(0 [µmol/l])
		P_1: S2|BigVial|Vial1|B|Concentration
		P_2: S2|BigVial|Vial1|C|Concentration

In S3, the formula is more complex, introducing a fraction parameter. This also leads to a duplication of references, including the Fract factor's (compare S3.txt):

Parameter: S3|BigVial|Vial1|SumMetab
	IsFixed: False
	Value: 0 [µmol/l]
	Formula: P_1*Fract + P_2*Fract
		P_1: S3|BigVial|Vial1|B|Concentration(0 [µmol/l])
		Fract: S3|BigVial|Vial1|Fract2(0.5)
		P_2: S3|BigVial|Vial1|C|Concentration(0 [µmol/l])
		P_1: S3|BigVial|Vial1|B|Concentration
		Fract: ..|Fract2
		P_2: S3|BigVial|Vial1|C|Concentration

So far, this does not appear to cause any problem, but might do so in certain instances.

[ManualModel.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/3217043/ManualModel.zip)

**Comment by Yuri05** [comment]
I think it's only the _text report itself_, which is wrong in Moby (refs are exported twice for all formulas)

**Comment by UlrichSi** [comment]
I am not sure. Try to open the project. If I do, I just noticed that I get the following error message:

Application:
MoBi 7.4.0.138

Unable to find a serializer for 'InContainerCondition'

Stack trace:
```
at OSPSuite.Serializer.Xml.XmlSerializerRepository`1.SerializerFor(XElement element)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.FormulaCacheXmlSerializer.TypedDeserialize(FormulaCache formulaCache, XElement formulaCacheNode, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.Extensions.XmlSerializerRepositoryExtensions.DeserializeFormulaCacheIn(IXmlSerializerRepository`1 serializerRepository, XElement element, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.BuildingBlockXmlSerializer`1.TypedDeserialize(TBuildingBlock bb, XElement element, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSpatialStructureXmlSerializer.TypedDeserialize(MoBiSpatialStructure spatialStructure, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlStaticMapper`2.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at MoBi.Core.Serialization.Xml.Serializer.MoBiSimulationXmlSerializer.TypedDeserialize(MoBiSimulation simulation, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.deserialize(XElement element, IMoBiProject project, Int32 version, Type type, SerializationContext parentSerializationContext)
   at MoBi.Core.Serialization.Xml.Services.XmlSerializationService.Deserialize[T](Byte[] compressedBytes, IMoBiProject project, SerializationContext serializationContext)
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.deserializeContent[T](MetaDataContent content, SerializationContext serializationContext)
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.addSimulationToProject(SimulationMetaData simulationMetaData, SerializationContext serializationContext)
   at MoBi.Core.Serialization.ORM.Mappers.ProjectMetaDataToProjectMapper.MapFrom(ProjectMetaData projectMetaData)
   at MoBi.Core.Serialization.ORM.ProjectPersistor.projectFrom(ProjectMetaData projectMetaData)
   at MoBi.Core.Serialization.ORM.ProjectPersistor.Load(IMoBiContext context)
   at MoBi.Core.Serialization.ORM.ContextPersistor.Load(IMoBiContext context, String projectFullPath)
   at MoBi.Presentation.Tasks.SerializationTask.<>c__DisplayClass10_0.<LoadProject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by Yuri05** [comment]
>Unable to find a serializer for 'InContainerCondition'

That's something different.
@msevestre Seems we have forgotten to increase MoBi project version
@UlrichSi Please open with [MoBi 8.0 beta (portable)](https://ci.appveyor.com/project/open-systems-pharmacology-ci/mobi/branch/develop/artifacts)

**Comment by UlrichSi** [comment]
Sorry, my fault - the wrong MoBi opened when loading the project.

**Comment by Yuri05** [comment]
but that way you found another bug - well done :)

**Comment by UlrichSi** [comment]
it's just a minefield, as so often... :-]

**Comment by UlrichSi** [comment]
What I was actually trying to accomplish is looking into other exports (PKML, XML, PDF) of simulation S3. They looks indeed clean, no sign of duplicate paths to me. - So it seems to be purely cosmetic in the TXT report.

**Comment by PavelBal** [comment]
I think this is not really duplicated. One entry is for how the alias is defined in the equation (e.g., including the relative paths), and the other entry is the resolved path with the value used in the simulation.

Not a bug but indeed confusing.
