### ISSUE TITLE
CSV/NonMem import crashes

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite.Core#983]
[ImportTestData.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6397343/ImportTestData.zip) 
[Theophylline_NMdat.zip](https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/files/6398486/Theophylline_NMdat.zip)

Tried different CSV formats (standard, german,..) and a NonMem-format. Every time:
```

Application:
PK-Sim® 10.0.0

The file format is not supported

Stack trace:
at OSPSuite.Infrastructure.Import.Core.DataSourceFileParser.For(String path)
   at OSPSuite.Infrastructure.Import.Services.Importer.LoadFile(IReadOnlyList`1 columnInfos, String fileName, IReadOnlyList`1 metaDataCategories)
   at OSPSuite.Presentation.Presenters.Importer.ImporterDataPresenter.SetDataSource(String dataSourceFileName)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.SetSourceFile(String path)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.SetDataSource(String dataSourceFileName)
   at OSPSuite.Presentation.Presenters.Importer.ImporterPresenter.<>c__DisplayClass17_0.<.ctor>b__0(Object s, SourceFileChangedEventArgs e)
   at System.EventHandler`1.Invoke(Object sender, TEventArgs e)
   at OSPSuite.Presentation.Presenters.Importer.SourceFilePresenter.OpenFileDialog(String initFileName)
   at OSPSuite.UI.Views.Importer.SourceFileControl.<.ctor>b__1_1()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

**Comment by georgeDaskalakis** [comment]
Part of this has to do with the file extensions: .nmdat was till now not supported (I have added it as a fix to this issue) and .CSV (in caps lock ) was also not supported. 

To import Theophylline a fix for the separator (#952) is still needed, since it uses spac as separator.
